<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRg7KGST\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRg7KGST/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRg7KGST.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRg7KGST\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRg7KGST\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Rg7KGST',
    'container.build_id' => '6ba7af33',
    'container.build_time' => 1590242771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRg7KGST');
