<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE35wbHK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE35wbHK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE35wbHK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE35wbHK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE35wbHK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E35wbHK',
    'container.build_id' => '77523a1d',
    'container.build_time' => 1589201732,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE35wbHK');
