<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmgPsLD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmgPsLD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmgPsLD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmgPsLD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUmgPsLD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UmgPsLD',
    'container.build_id' => '399c3650',
    'container.build_time' => 1590320098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmgPsLD');
